# Generated by Django 2.0.7 on 2018-07-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20180723_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('hidden', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Sex'),
        ),
    ]
