# Generated by Django 2.0.7 on 2018-07-31 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='products')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale', models.DecimalField(decimal_places=2, default='0', max_digits=4)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Category')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Sex')),
            ],
        ),
    ]
